
version: 0.1
env:
  parameter-store:
    AccessKey: "CB-AccessKey"
    SecretKey: "CB-SecretKey"
phases:
  build:
    commands:
      - echo Build started on `date`
      - terraform init environment
      - terraform plan -var "access_key=$AccessKey" -var "secret_key=$SecretKey" environment
  post_build:
    commands:
      - echo Build completed on `date`
