
version: 0.1
phases:
  build:
    commands:
      - echo Build started on `date`
      - terraform init environment
      - terraform plan environment
  post_build:
    commands:
      - echo Build completed on `date`
